### PR TITLE
Get fixes from upstream

### PR DESCRIPTION
**Pull request by skylord123**
barrycarey did an update that fixed an issue I was having. The docker image builds off this repo so please update it with this PR.

Thanks.

### CODE REVIEW

**Comment by subchromat** [comment]
I am also experiencing the same issue.

**Comment by atribe** [comment]
Thanks.

**Comment by n1nj4888** [comment]
Apologies for tagging onto this pull request but I can't seem to find a way of raising a new issue against the atribe/Speedtest-for-InfluxDB-and-Grafana docker...

I just updated the atribe/Speedtest-for-InfluxDB-and-Grafana image to the latest version and the container restarts because of the following errors immediately after starting the container - This didn't happen with the previous container/image so not sure what has changed here in this latest build?

Loading Configuration File config.ini
Configuration Successfully Loaded
2019-02-11 01:29:55,627 - DEBUG: Testing connection to InfluxDb using provided credentials

There are no other indicators as to why to container dies and it dies that quickly after starting that I can't seem to get into the container to find out why?

PS: I'm running the docker atribe/Speedtest-for-InfluxDB-and-Grafana:latest on Synology

Thanks!

**Comment by fanaticDavid** [comment]
@n1nj4888 I just upgraded the image (also on a Synology NAS), and I am encountering exactly the same issue as you: the container is stuck restarting. Here's a sample from the logs, obtained using Portainer:

```
Loading Configuration File config.ini
Configuration Successfully Loaded
2019-02-13 22:42:22,980 - DEBUG: Testing connection to InfluxDb using provided credentials
Loading Configuration File config.ini
Configuration Successfully Loaded
2019-02-13 22:42:50,590 - DEBUG: Testing connection to InfluxDb using provided credentials
Loading Configuration File config.ini
Configuration Successfully Loaded
2019-02-13 22:43:44,746 - DEBUG: Testing connection to InfluxDb using provided credentials
Loading Configuration File config.ini
Configuration Successfully Loaded
2019-02-13 22:44:47,671 - DEBUG: Testing connection to InfluxDb using provided credentials
```

If the speed test is even run at all, the results are certainly not being saved to InfluxDB.

**Pull request merged**
